kind: PersistentVolume
apiVersion: v1
metadata:
  name: mce-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/docker/data/pv0001_2g"

