kind: PersistentVolume
apiVersion: v1
metadata:
  name: gog-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/docker/data/pv0002_1g"

