apiVersion: v1
kind: Service
metadata:
  name: gog-server
  labels:
    run: gog-server
spec:
  selector:
    run: gog-server
  ports:
  - name: nodeexporter
    port: 9100
    targetPort: 9100
  - name: gog      
    port: 8080
    targetPort: 8080
  type: LoadBalancer

  



